import { createTranslator, type AbstractIntlMessages } from "next-intl";
import { routing, type SiteLocale } from "./routing";

/**
 * Message catalogues live in messages/<locale>/<namespace>.json — one file per
 * area of the site, so translations can be reviewed in manageable pieces.
 * messages/en/* is the source; the other five are generated by
 * scripts/i18n-translate.mts and committed.
 */
export const NAMESPACES = [
  "common",
  "home",
  "pricing",
  "triage",
  "legal",
  "intake",
  "portal",
  "guides",
  "validation",
  "email",
] as const;
export type Namespace = (typeof NAMESPACES)[number];

export type Messages = Record<Namespace, AbstractIntlMessages>;

export async function loadMessages(locale: string): Promise<Messages> {
  const l = (routing.locales as readonly string[]).includes(locale) ? locale : routing.defaultLocale;
  const entries = await Promise.all(
    NAMESPACES.map(async (ns) => [ns, (await import(`../../messages/${l}/${ns}.json`)).default] as const),
  );
  return Object.fromEntries(entries) as Messages;
}

/**
 * A translator outside React, keyed by plain strings (the catalogues are JSON
 * loaded at runtime, so there is no generated key type to check against).
 */
export interface ServerTranslator {
  (key: string, values?: Record<string, string | number | Date>): string;
  raw(key: string): unknown;
  has(key: string): boolean;
}

/**
 * A translator outside React rendering — for emails, PDFs and anything a route
 * handler or webhook produces in the STUDENT's language rather than the
 * request's.
 */
export async function translatorFor(locale: SiteLocale | string, namespace: Namespace): Promise<ServerTranslator> {
  const l = (routing.locales as readonly string[]).includes(locale) ? locale : routing.defaultLocale;
  return createTranslator({ locale: l, messages: await loadMessages(l), namespace }) as unknown as ServerTranslator;
}
