import { createTranslator, type AbstractIntlMessages } from "next-intl";
import { routing, type SiteLocale } from "./routing";

/**
 * Message catalogues live in messages/<locale>/<namespace>.json — one file per
 * area of the site, so translations can be reviewed in manageable pieces.
 * messages/en/* is the source; the other five are generated by
 * scripts/i18n-translate.mts and committed.
 */
export const NAMESPACES = [
  "common",
  "home",
  "pricing",
  "guide",
  "triage",
  "legal",
  "intake",
  "portal",
  "guides",
  "validation",
  "email",
] as const;
export type Namespace = (typeof NAMESPACES)[number];

export type Messages = Record<Namespace, AbstractIntlMessages>;

/**
 * Which catalogues each surface's CLIENT components read.
 *
 * The provider in [locale]/layout.tsx used to hand every client the whole
 * catalogue — 68 kB of JSON, 24 kB gzipped, serialised into the HTML of every
 * page in each of six languages. The home page's only client components are
 * the language switcher and a one-line <html lang> effect, so roughly 95% of
 * that never had a reader: `legal` (14 kB) and `home` (8.5 kB) are used
 * exclusively by server components and were shipped to the browser anyway.
 *
 * It matters more here than the number suggests. These are students who have
 * just landed, usually on a foreign SIM, often looking this up on data they
 * are paying roaming rates for.
 *
 * A route must list every namespace its client tree reads, including the ones
 * its children read — a missing one is a runtime error, not a fallback.
 * tests/i18n.test.ts fails if a client component starts using a namespace no
 * route provides.
 */
export const CLIENT_NAMESPACES = {
  /** The header and footer, on every page. */
  chrome: ["common"],
  /** TriageForm. */
  triage: ["common", "triage", "validation"],
  /** IntakeWizard, and every uploader and request-builder it embeds. */
  intake: ["common", "intake", "pricing", "portal", "validation"],
  /** The student's file: the same uploaders, plus the Tasa 012 guide. */
  portal: ["common", "guides", "intake", "portal", "pricing", "validation"],
} as const satisfies Record<string, readonly Namespace[]>;

/** The named catalogues only — what a route hands its NextIntlClientProvider. */
export function pick<T extends Record<string, unknown>>(
  messages: T,
  namespaces: readonly Namespace[],
): Partial<T> {
  return Object.fromEntries(
    namespaces.map((ns) => [ns, messages[ns as keyof T]]),
  ) as Partial<T>;
}

export async function loadMessages(locale: string): Promise<Messages> {
  const l = (routing.locales as readonly string[]).includes(locale) ? locale : routing.defaultLocale;
  const entries = await Promise.all(
    NAMESPACES.map(async (ns) => [ns, (await import(`../../messages/${l}/${ns}.json`)).default] as const),
  );
  return Object.fromEntries(entries) as Messages;
}

/**
 * A translator outside React, keyed by plain strings (the catalogues are JSON
 * loaded at runtime, so there is no generated key type to check against).
 */
export interface ServerTranslator {
  (key: string, values?: Record<string, string | number | Date>): string;
  raw(key: string): unknown;
  has(key: string): boolean;
}

/**
 * A translator outside React rendering — for emails, PDFs and anything a route
 * handler or webhook produces in the STUDENT's language rather than the
 * request's.
 */
export async function translatorFor(locale: SiteLocale | string, namespace: Namespace): Promise<ServerTranslator> {
  const l = (routing.locales as readonly string[]).includes(locale) ? locale : routing.defaultLocale;
  return createTranslator({ locale: l, messages: await loadMessages(l), namespace }) as unknown as ServerTranslator;
}
