import { describe, it, expect } from "vitest";
import { execFileSync } from "node:child_process";

describe("type gate", () => {
  /**
   * A red typecheck hides the next real type error in known noise. This keeps
   * it green on a fresh clone, where next-env.d.ts — gitignored, generated by
   * `next build` — does not exist.
   */
  it("compiles with no errors", () => {
    let output = "";
    let failed = false;
    try {
      execFileSync("npx", ["tsc", "--noEmit"], { encoding: "utf8", stdio: "pipe" });
    } catch (error) {
      failed = true;
      const e = error as { stdout?: string; stderr?: string };
      output = `${e.stdout ?? ""}${e.stderr ?? ""}`;
    }
    expect(failed, output).toBe(false);
  }, 180_000);
});
