/**
 * Regenerate src/lib/countries/es-names.generated.ts — the Spanish country
 * names printed on the official forms.
 *
 *   npx tsx scripts/generate-country-names.mts
 *
 * Names come from ICU (Intl.DisplayNames "es"), then OVERRIDES. The output is
 * committed rather than computed at runtime, so what prints on a police form
 * cannot change silently when a Node upgrade ships new ICU data. Review the
 * diff whenever you regenerate.
 */
import { writeFile } from "node:fs/promises";
import { COUNTRY_CODES } from "../src/lib/countries/codes.ts";

/** Where ICU's display name is wrong for an official form. */
const OVERRIDES: Record<string, string> = {
  CI: "COSTA DE MARFIL", // ICU: "Côte d’Ivoire" — Spanish administration uses the Spanish name
  HK: "HONG KONG", // ICU: "RAE de Hong Kong (China)"
  MO: "MACAO", // ICU: "RAE de Macao (China)"
  MM: "MYANMAR", // ICU: "Myanmar (Birmania)"
  UM: "ISLAS MENORES ALEJADAS DE LOS ESTADOS UNIDOS", // ICU abbreviates "EE. UU."
  VI: "ISLAS VÍRGENES DE LOS ESTADOS UNIDOS",
};

const es = new Intl.DisplayNames(["es"], { type: "region" });
const lines = COUNTRY_CODES.map((code) => {
  const name = (OVERRIDES[code] ?? es.of(code)!).toUpperCase();
  return `  ${code}: ${JSON.stringify(name)},`;
});

await writeFile(
  "src/lib/countries/es-names.generated.ts",
  `// GENERATED by scripts/generate-country-names.mts from ICU ${process.versions.icu}.
// Do not edit by hand: add an override in the script and regenerate.
import type { CountryCode } from "./codes";

export const SPANISH_FORM_NAMES: Record<CountryCode, string> = {
${lines.join("\n")}
};
`,
);
console.log(`Wrote ${COUNTRY_CODES.length} names (ICU ${process.versions.icu}).`);
