/**
 * Regenerate the committed country-name tables:
 *
 *   src/lib/countries/es-names.generated.ts       — the Spanish country names
 *                                                   printed on the official forms
 *   src/lib/countries/display-names.generated.ts  — the names shown in the
 *                                                   pickers, in every site locale
 *
 *   npm run countries:generate
 *
 * Names come from ICU (Intl.DisplayNames), then OVERRIDES for the forms. The
 * output is committed rather than computed at runtime:
 *   - what prints on a police form cannot change silently when a Node upgrade
 *     ships new ICU data;
 *   - the server and the browser render the same names in the same order.
 *     Node's and Chromium's ICU disagree (e.g. "Hong Kong SAR China" vs
 *     "Hong Kong"), and a picker computed from either breaks hydration.
 * Review the diff whenever you regenerate.
 */
import { writeFile } from "node:fs/promises";
import { COUNTRY_CODES } from "../src/lib/countries/codes.ts";
import { LOCALES } from "../src/i18n/routing.ts";

/** Where ICU's display name is wrong for an official form. */
const OVERRIDES: Record<string, string> = {
  CI: "COSTA DE MARFIL", // ICU: "Côte d’Ivoire" — Spanish administration uses the Spanish name
  HK: "HONG KONG", // ICU: "RAE de Hong Kong (China)"
  MO: "MACAO", // ICU: "RAE de Macao (China)"
  MM: "MYANMAR", // ICU: "Myanmar (Birmania)"
  UM: "ISLAS MENORES ALEJADAS DE LOS ESTADOS UNIDOS", // ICU abbreviates "EE. UU."
  VI: "ISLAS VÍRGENES DE LOS ESTADOS UNIDOS",
};

const header = `// GENERATED by scripts/generate-country-names.mts from ICU ${process.versions.icu}.`;

const es = new Intl.DisplayNames(["es"], { type: "region" });
const formLines = COUNTRY_CODES.map((code) => {
  const name = (OVERRIDES[code] ?? es.of(code)!).toUpperCase();
  return `  ${code}: ${JSON.stringify(name)},`;
});

await writeFile(
  "src/lib/countries/es-names.generated.ts",
  `${header}
// Do not edit by hand: add an override in the script and regenerate.
import type { CountryCode } from "./codes";

export const SPANISH_FORM_NAMES: Record<CountryCode, string> = {
${formLines.join("\n")}
};
`,
);

// Each locale's list is sorted here, once, so the order is pinned too: a
// runtime Intl.Collator would be one more place for two ICU builds to differ.
const displayBlocks = LOCALES.map((locale) => {
  const names = new Intl.DisplayNames([locale], { type: "region" });
  const collator = new Intl.Collator(locale);
  const rows = COUNTRY_CODES.map((code) => [code, names.of(code)!] as const).sort(
    (a, b) => collator.compare(a[1], b[1]),
  );
  const lines = rows.map(([code, name]) => `    [${JSON.stringify(code)}, ${JSON.stringify(name)}],`);
  return `  ${locale}: [\n${lines.join("\n")}\n  ],`;
});

await writeFile(
  "src/lib/countries/display-names.generated.ts",
  `${header}
// Do not edit by hand: regenerate with \`npm run countries:generate\`.
import type { SiteLocale } from "../../i18n/routing";
import type { CountryCode } from "./codes";

/** Every country's name in each site locale, sorted by name in that locale. */
export const COUNTRY_DISPLAY_NAMES: Record<SiteLocale, readonly (readonly [CountryCode, string])[]> = {
${displayBlocks.join("\n")}
};
`,
);

console.log(
  `Wrote ${COUNTRY_CODES.length} names × ${LOCALES.length} locales + Spanish form names (ICU ${process.versions.icu}).`,
);
